// Generated by https://quicktype.io

export interface RespuestaPosts {
  ok: boolean;
  pg: number;
  posts: Post[];
}

export interface Post {
  _id?: string;
  mensaje?: string;
  imgs?: string[];
  usuario?: Usuario;
  created?: string;
  /*  __v:     number; */
  /* img?:    any[]; */
}

export interface Usuario {
  _id?: string;
  nombre?: string;
  avatar?: string;
  email?: string;
  password?: string;
  /* __v?:    number; */
}
